{
  "name": "Jdp System 0.10 - Princesa Diamante",
  "short_name": "JdpSystem",
  "start_url": "/Jdp_system-0.10/",
  "display": "standalone",
  "icons": [
    {
      "src": "public/diamante.png", 
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "public/diamante-512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ]
}
