{
  "name": "Jdp System 0.10",
  "short_name": "JdpSystem",
  "start_url": "/Jdp_system-0.10/",
  "display": "standalone",
  "background_color": "#ffffff",
  "theme_color": "#000000",
  "icons": [
    {
      "src": "public/icon-192.png",
      "sizes": "192x192",
      "type": "image/png"
    }
  ]
} 
